source "https://rubygems.org"
gem "faraday", "~> 0.11.0"
gem "jekyll"
gem "compass"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-archives"
gem "jekyll-redirect-from"
gem "jekyll-gist"
gem "jekyll-import"
gem "jemoji"
gem "pry"
