Oh, Lisp, how I have loved thee, and missed thee.

I began using Lisp way way back in 1975, entering university. Eventually I became the maintainer of our Lisp interpretter. It was fun, but, alas, it didn't last. When I left uni, no one I worked for was using Lisp in any way, nor did I have access to any interpretters at the time.

Along about 1985, I began to work on unix systems, and adopted emacs as the editor/IDE for my work, in no small part because of elisp. 

I have missed the evolution of Lisp, now there are various forms of Common Lisp, Scheme, and others out there. A far cry from McCarthy's little monograph.

In this past year, I've poked at both ocaml and haskell, and thought fondly of my days writing Lisp programs, so I thought I'd at least set it up, give it a few friendly pokes, and see what comes out. :)

!!Links
* http://en.wikipedia.org/wiki/Common_Lisp -- my initial starting point
* http://common-lisp.net/ -- ground zero for stuff about Common Lisp, one of the two main dialects
* http://planet.lisp.org/ -- lisp blog aggregator
* http://www.cliki.net/ -- Common Lisp Wiki (the new beta version is at http://cliki-test.h4ck.me/ )
* http://www.mohiji.org/2011/01/modern-common-lisp-on-osx/ -- Getting CL set up on the mac -- recommended editor Aquamacs, but I like GNU Emacs much better.
* http://www.sbcl.org/platform-table.html -- Steel Bank Common Lisp is one of the more highly recommended versions of CL.
* http://www.quicklisp.org/ -- the CPAN/CTAN/PEAR/gems analog of CL, i.e., used to install whatever libraries or packages you may need for your Lisp application
* http://common-lisp.net/project/slime/ -- Superior Lisp Interaction Mode for emacs -- this is really essential, it gives you a REPL for lisp inside emacs.
* http://cliki-test.h4ck.me/Current%20recommended%20libraries -- a list of currently recommended libraries for building Lisp applications.
* http://www.lispworks.com/documentation/HyperSpec/Front/ -- Common Lisp Reference Specification


>>comment<<
Summary:A collection of things about Lisp, the wonderful language invented by the late John McCarthy
Parent:(Technology.)Languages
IncludeMe:[[(Technology.)Languages]]
Categories:[[!Links]],[[!Collections]]
Tags: programming languages, lisp
(:tags-hide programming languages, lisp :)
>><<

