!!Links:
(You really need both of these together: )
* https://developer.mozilla.org/en/JavaScript
* https://developer.mozilla.org/en/DOM


>>comment<<
Summary:Notes about JavaScript
Parent:(Technology.)Languages
IncludeMe:[[Technology.Languages]]
Tags: javascript, languages, software, programming, web development
(:tags javascript, languages, software, programming, web development:)
Categories:[[!Collections]], [[!Links]]
>><<

